### ISSUE TITLE
右键菜单有错位

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/deepin-menu#1]
<a href="https://github.com/zhuzilinuser"><img src="https://avatars.githubusercontent.com/u/12298476?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @zhuzilinuser**
_Tuesday Jan 26, 2016 at 12:29 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/235_

---

![20160126202658](https://cloud.githubusercontent.com/assets/12298476/12580545/66310ccc-c46b-11e5-8728-8c3dcfb7d418.png)
还有启动器里面的右键。

**Comment by manateelazycat** [comment]
This bug has fixed in lastest version.
