### ISSUE TITLE
Issue on ubuntu 19

### ISSUE THREAD

**Issue by filipehdbr** [linuxdeepin/deepin-menu#11]
qt.qpa.plugin: Could not load the Qt platform plugin "dxcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: dxcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
