### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by konstyab** [linuxdeepin/deepin-menu#2]
add LICENSE file showing which livense is deepin-menu under. Like GPLv3

**Comment by 1dot75cm** [comment]
Please add LICENSE file, Otherwise, it can not be packaged. [BZ#1419330](https://bugzilla.redhat.com/show_bug.cgi?id=1419330) @hualet

**Comment by hualet** [comment]
OK, it should've been declared. I'll do it tomorrow.

**Comment by hualet** [comment]
I've added a README and declared the license being used instead of a LICENSE file, because all deepin projects share the same README template.

**Comment by 1dot75cm** [comment]
I need to reference a LICENSE **file**, please add this file to [linuxdeepin/developer-center](https://github.com/linuxdeepin/developer-center/).  @hualet

**Comment by hualet** [comment]
Sorry, I don't get it, the license statement in the README is not enough ? the LICENSE file it's referring doesn't serve what you want ?

**Comment by 1dot75cm** [comment]
Sorry, i'm late.

I need a LICENSE file in the project directory. I can package it in the `/usr/share/doc/PROJECT/` directory. Fedora Packaging Guidelines recommends that the project should included a LICENSE file.

I see that many Deepin projects do not have LICENSE files, so I can hardly continue to package these projects now.

Please see https://github.com/FZUG/repo/issues/53 for the package progress.

Thanks for your hard work.   @hualet

**Comment by hualet** [comment]
No problem, I'll send gerrit CLs to deepin projects that don't have the LICENSE file.

**Comment by hualet** [comment]
@1dot75cm deepin projects should all have a LICENSE file in their repositories now.

**Comment by 1dot75cm** [comment]
Thanks. @hualet
